# Thief Detector
## This task tests your Image Processing skills to build a motion detection algorithm that alarms you when you have an unwanted visitor in your home.

## Get live video feed from webcam

In [2]:
import cv2
import numpy as np

In [3]:
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video', gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

## Read first frame, convert to Grayscale and store it as reference background image

In [4]:
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    background = gray
    # save the background image
    cv2.imwrite('background.jpg', background)
    break

## Compute Absolute Difference between Current and First frame

In [5]:
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(background, gray)
    print(diff)
    cv2.imshow('Video', gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[ 52  67  62 ... 115 110 110]
 [ 55  72  62 ... 107 102 104]
 [ 60  69  62 ... 110 110 112]
 ...
 [ 18  18  19 ...  96  88  78]
 [ 14  23  26 ...  99  88  80]
 [ 20  25  25 ...  88  88  84]]
[[ 74  76  80 ... 140 139 139]
 [ 70  76  77 ... 137 138 138]
 [ 74  77  77 ... 140 140 139]
 ...
 [ 34  43  45 ... 133 129 122]
 [ 30  37  41 ... 130 127 122]
 [ 32  31  36 ... 120 130 127]]
[[ 84  84  86 ... 149 147 152]
 [ 83  86  86 ... 145 147 152]
 [ 81  90  86 ... 148 151 149]
 ...
 [ 33  40  44 ... 139 134 133]
 [ 31  35  39 ... 130 137 135]
 [ 35  31  36 ... 128 132 134]]
[[ 86  87  89 ... 159 157 160]
 [ 82  88  90 ... 156 157 160]
 [ 86  88  91 ... 158 159 158]
 ...
 [ 40  45  51 ... 146 145 144]
 [ 37  43  50 ... 140 143 143]
 [ 39  41  46 ... 138 139 139]]
[[ 92  90  92 ... 163 162 164]
 [ 92  96  97 ... 161 164 167]
 [ 95  97  98 ... 163 165 162]
 ...
 [ 44  51  54 ... 146 149 150]
 [ 44  47  51 ... 142 146 148]
 [ 45  45  50 ... 140 140 144]]
[[ 91  92  91 ... 170 169 172]
 [ 90  96

## Apply threshold

In [11]:
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(background, gray)
    thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)[1]
    cv2.imshow('Video', thresh)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

## Find contours 

In [ ]:
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(background, gray)
    thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)[1]
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        if cv2.contourArea(contour) > 2000:
            (x, y, w, h) = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

## Check if contourArea is large and draw rectangle around the object, output "UNSAFE" text in red color

In [10]:
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(background, gray)
    thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)[1]
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        if cv2.contourArea(contour) > 2000:
            (x, y, w, h) = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
            cv2.putText(frame, "Thief Detected", (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 0, 255), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

## Display images

In [4]:
import uuid
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(background, gray)
    thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)[1]
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        if cv2.contourArea(contour) > 30000:
            (x, y, w, h) = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
            cv2.putText(frame, "Thief Detected", (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 0, 255), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

## Release objects

In [5]:
video = cv2.VideoCapture(0)

width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
out = cv2.VideoWriter('data/output.mp4', fourcc, 24, (width, height))

thiefIsInside = False

In [9]:
import uuid
from IPython.display import Video
video_capture = cv2.VideoCapture(0)
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(background, gray)
    thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)[1]
    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        if cv2.contourArea(contour) > 2000:
            (x, y, w, h) = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
            cv2.putText(frame, "Thief Detected", (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
            thiefIsInside = True
        else:
            thiefIsInside = False

    if thiefIsInside:
        out.write(frame)
    else:
        out.release()
        out = cv2.VideoWriter('data/output.mp4', fourcc, 24, (width, height))
          
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


video_capture.release()
cv2.destroyAllWindows()